name: Build Sideload IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.5' # Pinning to the exact recommended version

      - name: Get Dependencies
        run: |
          flutter pub upgrade # This helps resolve minor version mismatches automatically
          flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create IPA Structure
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r LuCI_Mobile_Unsigned.ipa Payload
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Luci-Mobile-IPA
          path: LuCI_Mobile_Unsigned.ipa
